FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install uv
RUN pip install uv

COPY pyproject.toml /app/pyproject.toml
COPY README.md /app/README.md
COPY src /app/src
COPY config /app/config

# Install dependencies from pyproject.toml
RUN uv sync

# Expose port for Streamlit
EXPOSE 8501

# Run Streamlit app
CMD ["uv", "run", "streamlit", "run", "src/apps/app_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
