services:
  drift_reporter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.drift_detector
    container_name: drift_detector
    depends_on:
      - rabbitmq
    volumes:
      - ../.drift_reports:/app/.drift_reports
      - ../.tracker:/app/.tracker
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: cancer-predict-api
    ports:
      - "8000:8000"
    depends_on:
      - drift_reporter
      - rabbitmq
    volumes:
      - ../.tracker:/.tracker
    restart: unless-stopped

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    container_name: cancer-predict-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ../.drift_reports:/.drift_reports
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
