artifacts:
  base_path: artifacts
  
data:
  test_size: 0.2
  random_state: 42

drift:
  buffer_size: 5
  path: ../../../.drift_reports

experiment_tracker:
  params:
    experiment_name: breast_cancer_ml

defaults:
  - experiment_tracker: wandb
  - model: logistic_regression
