data:
  path: ../../../data/bank/train.csv
  random_state: 42
  target: y
  test_size: 0.2

drift:
  buffer_size: 5
  path: ../../../.drift_reports

experiment_tracker:
  params:
    experiment_name: bank

scoring: roc_auc

defaults:
  - experiment_tracker: local
  - model: logistic_regression
